#!/bin/bash

for pkg in jq curl; do
    if ! which $pkg 2>&1 >/dev/null ; then
        echo Install $pkg
        exit 1
    fi
done

usage() {
    cat <<EOM
$0 [ -o OUT_DIR ] [ --range n-m ] [--unsafe]
EOM
}

OUT_DIR=/tmp/cat_fr
RANGE="1-115"
UNSAFE=0

while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help )
            usage
            exit
            ;;
        -o )
            OUT_DIR=${2%/}
            shift 2
            ;;
        --range )
            RANGE=$2
            shift 2
            ;;
        --unsafe )
            UNSAFE=1
            shift
            ;;
        * )
            usage
            exit 1
            ;;
    esac
done

echo "* nbt files will be output to $OUT_DIR"
mkdir -p $OUT_DIR
BASIC_AUTH=negainoido:icfpc_ojima

range() {
    echo $1 | sed 's/\([0-9]*\)-\([0-9]*\)/seq \1 \2/g' | sh
}

best() {
    URL=http://${BASIC_AUTH}@35.196.88.166/list_solution/json?problem=$1
    curl -s "$URL" |
    jq -r '.value.solutions[] | if .score > 0 then "\(.score) \(.id) \(.solver_id)" else empty end ' |
    sort -n | head -1
}

for i in $(range "$RANGE"); do

    I=$(printf "%03d" $i)
    OUT="$OUT_DIR/FR${I}.nbt"
    echo "* cat-best $I > $OUT"

    best "PD$I" | (

        read SCORE ID SOLVER_D
        echo "** D: $ID $SOLVER_D"
        PD_URL="http://${BASIC_AUTH}@35.196.88.166/static/solutions/${ID}.nbt"

        best "PA$I" | (

            read SCORE ID SOLVER_A
            echo "** A: $ID $SOLVER_A"
            PA_URL="http://${BASIC_AUTH}@35.196.88.166/static/solutions/${ID}.nbt"

            # concat PD+PA
            (
                curl -s "$PD_URL" | head -c -1
                curl -s "$PA_URL"
            ) >$OUT

            # submit
            URL="http://${BASIC_AUTH}@35.196.88.166/submit_solution"
            echo $URL

            if [ $UNSAFE -eq 0 ]; then
                curl "$URL" -F problem_id=FR${I} -F solver_id="bestcat--${SOLVER_D}--${SOLVER_A}" -F comment=best_cat -F nbt=@${OUT} > /dev/null
            else
                curl "$URL" -F problem_id=FR${I} -F solver_id="unsafe_bestcat--${SOLVER_D}--${SOLVER_A}" -F comment=best_cat -F nbt=@${OUT} > /dev/null
            fi

        )

    )

done
